### ISSUE TITLE
Client network socket disconnected before secure TLS connection

### ISSUE THREAD

**Issue by bvanhou** [Nerixyz/instagram_mqtt#10]
Have you seen this kind of error before?

```
ERROR	Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:299:28)
    at TLSSocket.emit (events.js:215:7)
    at TLSSocket.EventEmitter.emit (domain.js:476:20)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET',
  path: undefined,
  host: 'edge-mqtt.facebook.com',
  port: 443,
  localAddress: undefined
}
```

**Comment by Nerixyz** [comment]
This is 99% not the fault of this library. Make sure other requests get through (to other hosts) and "raw" TLS sockets are allowed.

**Comment by bvanhou** [comment]
Thanks, for clarifying. I am still new to this. What front end languages are you using for using this?

**Comment by Nerixyz** [comment]
I'm using regular typescript (transpiled to javascript).
