### ISSUE TITLE
Random issue occurs

### ISSUE THREAD

**Issue by bvanhou** [Nerixyz/instagram_mqtt#13]
I have seen this error occur randomly a few times and working fine for weeks. I am unable to pin point the cause. Any Ideas? Have you seen this before?

```
Error: This socket has been ended by the other party
at TLSSocket.writeAfterFIN [as write] (net.js:396:12)
at MQTToTClient.writePacketToSocket (/usr/src/app/node_modules/instagram_mqtt/dist/mqtt/mqtt.client.js:179:21)(/usr/src/app/node_modules/instagram_mqtt/dist/mqtt/mqtt.client.js:160:22)
at MQTToTClient.startFlow (/usr/src/app/node_modules/instagram_mqtt/dist/mqtt/mqtt.client.js:96:22)
```

**Comment by Nerixyz** [comment]
Could you try [this](https://github.com/Nerixyz/instagram_mqtt#debugging) with the latest version and paste your log here?

**Comment by bvanhou** [comment]
Ok, I will try it! Ohh additionally, do you know how I could kill the client? So when certain conditions are met the realtime mqtt shutsdown

**Comment by Nerixyz** [comment]
See #18
