### ISSUE TITLE
Using library

### ISSUE THREAD

**Issue by amirpdlll** [Nerixyz/instagram_mqtt#16]
Hello,
Sorry to ask stupid question but I'm newbie in node js

I have downloaded the source and Installed modules and using tsc example.ts in command line I have compiled example file 'ts' to ' js' , but when I execute this file using 'node example' I face this error :
```

(node:3284) UnhandledPromiseRejectionWarning: TypeError: Class constructor IgApiClient cannot be invoked without 'new'
    at new IgApiClientExt (C:\nodejs\realTime\src\extend.js:59:28)
    at assertClient (C:\nodejs\realTime\src\extend.js:176:16)
    at Object.withRealtime (C:\nodejs\realTime\src\extend.js:168:14)
    at C:\nodejs\realTime\realts.js:48:28
    at step (C:\nodejs\realTime\realts.js:33:23)
    at Object.next (C:\nodejs\realTime\realts.js:14:53)
    at C:\nodejs\realTime\realts.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\nodejs\realTime\realts.js:4:12)
    at C:\nodejs\realTime\realts.js:43:23
    at Object.<anonymous> (C:\nodejs\realTime\realts.js:119:7)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
(node:3284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

I know it is stupid question but I need some help to work on this project , thanks

**Comment by Nerixyz** [comment]
- How did you compile the example?
- How does the `extend.js` file look (esp. the lines in the error)?

**Comment by amirpdlll** [comment]
1.using command 'tsc example.ts' in command line (windows)
2.this is example.js after compiling 
https://prnt.sc/qxlkq3
https://prnt.sc/qxll0f

and this is example.ts
https://prnt.sc/qxll75


thanks

**Comment by amirpdlll** [comment]
Is there a bug in library 

> * How did you compile the example?
> * How does the `extend.js` file look (esp. the lines in the error)?

is there a bug in library or I made mistake ?

**Comment by Nerixyz** [comment]
I'd guess the tsc compiles to es3 by default and there's the problem. However you can use the example in any other project. You just have to install instagram_mqtt.
