### ISSUE TITLE
Consistent fbns fail

### ISSUE THREAD

**Issue by Ektaros** [Nerixyz/instagram_mqtt#42]
When calling fbns.connet() there is and unhandeled error and fbns fails to connect. This is consistent and happens every time, but not with every account. Started seeing such behavior 1 day ago.
Here are the logs. Just for sience tried using code from example - same result
```
ig:state Deserializing state of type object +0ms
  ig:state Deserializing cookies, supportedCapabilities, language, timezoneOffset, radioType, capabilitiesHeader, connectionTypeHeader, isLayoutRTL, adsOptOut, thumbnailCacheBustingValue, clientSessionIdLifetime, pigeonSessionIdLifetime, deviceString, deviceId, uuid, phoneId, adid, build, igWWWClaim, passwordEncryptionKeyId, passwordEncryptionPubKey, authorization +22ms
  ig:request Requesting GET /api/v1/direct_v2/get_presence/ +0ms
  ig:mqtt:fbns Connecting to FBNS... +0ms
  ig:mqtt:fbns Constructing connection +2ms
  ig:mqtt:mqttot mqtt-mini.facebook.com:443: Creating client +0ms
  mqtt:client Connecting... +0ms
  mqtt:client:packet Sent MQTToTConnectRequestPacket +0ms
  mqtt:client:packet Received ConnectResponsePacket +114ms
  mqtt:client Connected! +152ms
  ig:mqtt:fbns Connected to MQTT +176ms
  mqtt:client Starting keep-alive-ping {delay: 59.5} +26ms
  mqtt:client:packet Sent SubscribeRequestPacket id: 1 topic: 76 +35ms
unhandledRejection TypeError: Cannot read property 'toString' of undefined
    at SafeSubscriber._next (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\instagram_mqtt\src\fbns\fbns.client.ts:102:41)
    at SafeSubscriber.__tryOrUnsub (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\node_modules\rxjs\src\internal\Subscriber.ts:265:10)    
    at SafeSubscriber.next (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\node_modules\rxjs\src\internal\Subscriber.ts:207:14)
    at Subscriber._next (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\node_modules\rxjs\src\internal\Subscriber.ts:139:22)
    at Subscriber.next (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\node_modules\rxjs\src\internal\Subscriber.ts:99:12)
    at Subject.next (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\node_modules\rxjs\src\internal\Subject.ts:70:17)
    at MQTToTClient.handlePacket (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\src\mqtt.client.ts:305:31)
    at C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\src\mqtt.client.ts:292:43
    at Array.forEach (<anonymous>)
    at MQTToTClient.parseData (C:\Users\mi\Documents\repos\channels-manager-instagram\node_modules\mqtts\src\mqtt.client.ts:292:25)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
the raw `res` in `this.client.$connect.subscribe` callback : 
```
ConnectResponsePacket {
  packetFlags: 0,
  remainingPacketLength: 2,
  _packetType: 2,
  _flags: 0,
  _returnCode: 2
}
```
Something chaneged on isntagram's side?

**Comment by Nerixyz** [comment]
There's no payload. This is now properly rejected (0.2.9).

**Comment by Nerixyz** [comment]
Reset your fbns state.
Added notice in `0.2.10`.

**Comment by Ektaros** [comment]
Thanks for the updates. Tested it here are the results:
 
New `Empty auth packet. Try resetting your fbns state!` is stiil an unhandeled rejection. I think it sould reject the original `fbns.connect` promise if possible or not throw the error (cause it is useless anyway) and just return. Emitted notice should be enought.

If by 'reset fbns state' you mean create a new FbnsClient - this has no effect. Connection still fails.
If not can u explain what exactly u mean by 'reset fbns state'?

**Comment by Nerixyz** [comment]
> is stiil an unhandeled rejection

This is now rejected earlier.


> If by 'reset fbns state' you mean create a new FbnsClient - this has no effect.

You are probably loading the auth. Don't do this. If you use ig.importState(), you can delete the fbns key. Currently, the client is somewhat unstable only 50% of connections succeed.

**Comment by Ektaros** [comment]
Yes it is unstable indeed.
Solved by using promise.race with timeouts and infinite retrying.
Any ideas on what could be the reason of instability?

**Comment by Nerixyz** [comment]
> Any ideas on what could be the reason of instability?

I don't know. Probably some race condition.

**Comment by Ektaros** [comment]
In new 0.2.11 there are no unhandled rejections but succesful realtime.connect() npw emits error
```
error: {
    name: 'Error',
    message: 'CONNACK returnCode: 0 errorName: Connection accepted',
    stack: 'Error: CONNACK returnCode: 0 errorName: Connection accepted\n' +
      '    at Object.next (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\instagram_mqtt\\src\\mqttot\\mqttot.client.ts:78:24)\n' +       
      '    at MQTToTClient.continueFlows (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:271:49)\n' +
      '    at MQTToTClient.handlePacket (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:358:19)\n' +
      '    at C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:310:43\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at MQTToTClient.parseData (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:310:25)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
  }
```

**Comment by Nerixyz** [comment]
> but succesful realtime.connect() now emits error

Your payload is probably empty. There's now a proper error and the fbns client should now be more stable.

**Comment by Ektaros** [comment]
The payload is empty indeed. Here is how the packet looks:
```
ConnectResponsePacket {
  packetFlags: 0,
  remainingPacketLength: 2,
  _packetType: 2,
  _flags: 0,
  _returnCode: 0
}
```
But this error seems to be a mistake cause realtime client work properly:
```
  ig:mqtt:realtime Connecting to realtime-broker... +0ms
  ig:mqtt:realtime Overriding:  +2ms
  ig:mqtt:mqttot edge-mqtt.facebook.com:443: Creating client +0ms
  mqtt:client Connecting... +0ms
  mqtt:client:packet Sent MQTToTConnectRequestPacket +0ms
  mqtt:client:packet Received ConnectResponsePacket +164ms
  mqtt:client Connected! +268ms
  mqtt:client Starting keep-alive-ping {delay: 19.5} +3ms
  ig:mqtt:realtime Connected. Checking initial subs. +306ms
  ig:mqtt:realtime Subscribing with Skywalker to ig/u/v1/19787707664 +1ms
  ig:mqtt:realtime Iris Sub to: seqId: 2444, snapshot: 1585415906280 +1ms
error: {
    name: 'Error',
    message: 'CONNACK returnCode: 0 errorName: Connection accepted',
    stack: 'Error: CONNACK returnCode: 0 errorName: Connection accepted\n' +
      '    at Object.next (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\instagram_mqtt\\src\\mqttot\\mqttot.client.ts:79:10)\n' +       
      '    at MQTToTClient.continueFlows (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:271:49)\n' +
      '    at MQTToTClient.handlePacket (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:358:19)\n' +
      '    at C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:310:43\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at MQTToTClient.parseData (C:\\Users\\mi\\Documents\\repos\\channels-manager-instagram\\node_modules\\mqtts\\src\\mqtt.client.ts:310:25)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)'
}
  mqtt:client:packet Sent PublishRequestPacket id: 1 topic: 88 +53ms
  mqtt:client:packet Sent PublishRequestPacket id: 2 topic: 134 +1ms
  mqtt:client:packet Received PublishAckPacket id: 1 +140ms
  mqtt:client:packet Received PublishRequestPacket topic: 150 +12ms
  mqtt:client:packet Received PublishAckPacket id: 2 +56ms
  mqtt:client:ping PingPong @ 1585415926524 +0ms
  mqtt:client:ping PingPong @ 1585415946026 +20s
  mqtt:client:packet Received PublishRequestPacket id: 6419 topic: 88 +53s --someone is writing
  mqtt:client:packet Sent PublishAckPacket id: 6419 +1ms
  mqtt:client:packet Received PublishRequestPacket id: 6420 topic: 146 +808ms --recieved a message
  mqtt:client:packet Sent PublishAckPacket id: 6420 +2ms
```

**Comment by Nerixyz** [comment]
> realtime client

Would be nice to say that earlier.

**Comment by Ektaros** [comment]
I did 
![image](https://user-images.githubusercontent.com/40774894/77829816-7ba77980-7135-11ea-9d99-36587f9952c6.png)

**Comment by Nerixyz** [comment]
> 
> 
> I did
> ![image](https://user-images.githubusercontent.com/40774894/77829816-7ba77980-7135-11ea-9d99-36587f9952c6.png)

nvm it's fixed now

**Comment by Ektaros** [comment]
Nice ty. Back to testing :)
