### ISSUE TITLE
Invalid state requested

### ISSUE THREAD

**Issue by andresespinosapc** [Nerixyz/instagram_mqtt#58]
I sometimes get this error:

```
(node:60) Error: Invalid state requested (current: 3, requested: 3)
    at MQTToTClient.next (/usr/ig_chatbot/node_modules/instagram_mqtt/node_modules/mqtts/src/mqtt.base-client.ts:61:19)
    at MQTToTClient.setDisconnected (/usr/ig_chatbot/node_modules/instagram_mqtt/node_modules/mqtts/src/mqtt.base-client.ts:100:14)
    at MQTToTClient.setDisconnected (/usr/ig_chatbot/node_modules/instagram_mqtt/node_modules/mqtts/src/mqtt.client.ts:408:15)
    at /usr/ig_chatbot/node_modules/instagram_mqtt/node_modules/mqtts/src/mqtt.client.ts:210:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I don't know how to reproduce it yet, but I'm trying to.

Have anyone got this error too?

**Comment by Nerixyz** [comment]
This error is basically saying, the client was disconnected and is set to disconnected again.

**Comment by andresespinosapc** [comment]
Perfect, that was the problem and I could solve it. Thanks!
