### ISSUE TITLE
Unfortunately, still an issue with module 'chance'

### ISSUE THREAD

**Issue by bvanhou** [Nerixyz/instagram_mqtt#9]
I have been able to set everything successfully, until I go into my serverless infrastructure. I am hoping that you could help me figure out what could be the cause.  

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'chance'",
    "trace": [
        "Runtime.ImportModuleError: Error: Cannot find module 'chance'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
        "    at Module.load (internal/modules/cjs/loader.js:653:32)",
        "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
        "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
        "    at startup (internal/bootstrap/node.js:283:19)"
    ]
}
```

**Comment by Nerixyz** [comment]
I've added it to the package.json. But it should also be installed by the `instagram-private-api`.

**Comment by bvanhou** [comment]
Great! How often does the npm package update?
